version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: synapse_postgres
    environment:
      POSTGRES_DB: synapse_db
      POSTGRES_USER: synapse_user
      POSTGRES_PASSWORD: synapse_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - synapse_network

  redis:
    image: redis:7-alpine
    container_name: synapse_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - synapse_network
    command: redis-server --appendonly yes

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: synapse_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://synapse_user:synapse_pass@postgres:5432/synapse_db
      REDIS_URL: redis://redis:6379
      ENVIRONMENT: development
      DEBUG: "True"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    networks:
      - synapse_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: synapse_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:8000/api
      REACT_APP_ENVIRONMENT: development
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    networks:
      - synapse_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: synapse_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - synapse_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  synapse_network:
    driver: bridge